#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  host-url: http://localhost:8080
  test-mail: ${SPRING_MAIL_SERVER_USERNAME}
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100


spring:

  jpa:
    show-sql: true
    open-in-view: false


    hibernate:
      ddl-auto: validate


    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    hikari:
      connection-timeout: 30000  # 30 секунд
      minimum-idle: 5
      maximum-pool-size: 10
    url: ${SPRING_DATASOURCE_DB_URL}
    username: ${SPRING_DATASOURCE_DB_USERNAME}
    password: ${SPRING_DATASOURCE_DB_PASSWORD}

  liquibase:
    changeLog: "classpath:db/changelog.sql"

  # Jackson Fields Serialization
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users
    caffeine.spec: maximumSize=10000,expireAfterAccess=5m

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${SPRING_OAUTH_GITHUB_CLIENT_ID}
            client-secret: ${SPRING_OAUTH_GITHUB_CLIENT_SECRET}
            scope:
              - email
          google:
            client-id: ${SPRING_OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          gitlab:
            client-id: ${SPRING_OAUTH_GITLAB_CLIENT_ID}
            client-secret: ${SPRING_OAUTH_GITLAB_CLIENT_SECRET}
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email

  sql:
    init:
      mode: always
      data-locations: "classpath:data4dev/data.sql"

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: ${SPRING_MAIL_SERVER_HOST}
    username: ${SPRING_MAIL_SERVER_USERNAME}
    password: ${SPRING_MAIL_SERVER_PASSWORD}
    port: ${SPRING_MAIL_SERVER_PORT}
  thymeleaf.check-template-location: false

  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

logging:
  level:
    root: debug
    com.javarush.jira: debug
    com.javarush.jira.common.config.MvcConfig: debug
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug

server:
  #  https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
springdoc.swagger-ui.path: /doc




